### ISSUE TITLE
Create a GitHub Wiki

### ISSUE THREAD

**Issue by smrubin** [NIEM/Movement#19]
Possible items for the Wiki include:
* Overview of the tool
* Setting up Docker
* Running all Docker containers locally and/or in the cloud
* Contributing guide / Code of conduct
* Tutorials
* App architecture and/or pipeline architecture diagrams
* Code examples
* Usage examples

**Comment by cdmgtri** [comment]
A wiki has been started with instructions on how to update Movement with a new NIEM release and how to deploy.

User guide-related information is available at https://niem.github.io/reference/tools/movement/.
