### ISSUE TITLE
Prevent infinite tree expansion for recursive elements.

### ISSUE THREAD

**Issue by smrubin** [NIEM/Movement#2]
Some elements in the data model may be infinitely recursive, meaning there is a loop with an element's type potentially having that same element as a child.

This looping allows a user to continue to expand the tree on the frontend without any sort of prevention or error.

Some mechanism should be in place to help prevent users from taking this action from both a UX and performance perspective.

**Comment by cdmgtri** [comment]
The current behavior seems acceptable since it is up to the user whether or not to manually expand the tree and the loop does not continue on its own automatically.
